### ISSUE TITLE
Errors in pacman-steem

### ISSUE THREAD

**Issue by ayobami99** [netuoso/pacman-steem#3]
I noticed some errors when interacting with the https://pacman.steemliberator.com which is a mini game that pays in steem for playing the games. All of these errors are those things that when adequately dealt with can improve user experience.

#  Sound
When you visit the website on a mobile, and the sound is readily on silent,
![20171225_154224_rmedited.jpg](https://res.cloudinary.com/hpiynhbhq/image/upload/v1514213007/qmoiql6rkyuy2n3fiujx.jpg)

But when you tap the sound icon which was on silent, it turns into a speaker mode meaning its not on silent:
![20171225_154234_rmedited.jpg](https://res.cloudinary.com/hpiynhbhq/image/upload/v1514213025/r5gl5gf8ruvrnvtmrdpu.jpg)

As you continue to play the game you notice that there is no sound, as the game is on silent and there is no sound in the game.
This should be dealth with as soon as possible.

# Vibration
When the game is started, at the press of the control or arrow keys, the mobile device vibrates. 
![20171225_154254_rmedited.jpg](https://res.cloudinary.com/hpiynhbhq/image/upload/v1514213053/kuo3akm9mt6nfakbyp7w.jpg)

As many times as the keys are pressed, the mobile device vibrates. This slows down the interactivity of the controls or makes the control hard to manipulate. The vibration is actually too much.

## Solution
There should be a setting to activate or de activate the vibration and the vibration should not be as intense as it is now.

# Swipe controls
![20171225_154254_rmedited.jpg](https://res.cloudinary.com/hpiynhbhq/image/upload/v1514213074/ec4qz4d0x7pv5ly3itqs.jpg)

Other alternative method to control the game is by swiping the screen. This does not work for any where on the screen, when you try to swipe on the game area on the screen, the game pauses. And when you try to swipe on the arrow keys, this literally does not work as this interferes with the controls.

## Solution
There should be a setting where the user can select or toggle between swipe control or key pad controls. 

# Video details of the error
https://youtube.com/watch?v=phVu59IpjFI&feature=youtu.be

# Browser details
I am using infinix hot 5 and accessing the page with chrome:
![Screenshot_20171225-154501.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1514213143/g39alv4s7hlsf9hoiexu.png)

Thank you

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@ayobami99/errors-in-pacman-steem">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by netuoso** [comment]
Closing as known will not fix.

The game is based on source from https://github.com/platzhersh/pacman-canvas.
